ktor:
  application:
    modules:
      - com.ravert.www.guitar_trainer.ApplicationKt.module
  deployment:
    port: ${?PORT}
    host: "0.0.0.0"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password